# Generated by Django 4.2.11 on 2024-03-29 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringToken",
            fields=[
                (
                    "token_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="authtoken.token",
                    ),
                ),
                ("expiration", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Expiring Token",
                "verbose_name_plural": "Expiring Tokens",
            },
            bases=("authtoken.token",),
        ),
    ]
