# Generated by Django 4.2.11 on 2024-03-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clrmodel",
            name="filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="portstatus",
            name="filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shipmentstatus",
            name="filename",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
