# Generated by Django 4.2.11 on 2024-05-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(default="Lachine", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
