# Generated by Django 4.2.11 on 2024-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_alter_user_company_name_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(max_length=40),
        ),
    ]
