# Generated by Django 4.2.11 on 2024-03-29 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_clrmodel_filename_portstatus_filename_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="id",
            new_name="uid",
        ),
    ]
