# Generated by Django 4.2.11 on 2024-05-02 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0002_expiringtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addcity",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="identifier",
                    ),
                ),
                ("bl", models.CharField(max_length=300)),
                ("truck", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("date", models.DateField()),
            ],
        ),
    ]
