# Generated by Django 4.2.11 on 2024-05-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0003_addcity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentstatus",
            name="attachment",
            field=models.TextField(),
        ),
    ]
