# Generated by Django 4.2.11 on 2024-05-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0003_alter_user_mobile_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="clrmodel",
            name="bls",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clrmodel",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
