# Generated by Django 4.2.11 on 2024-05-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0004_alter_shipmentstatus_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portstatus",
            name="attachment",
            field=models.TextField(),
        ),
    ]
