# Generated by Django 4.2.11 on 2024-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0005_alter_portstatus_attachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="citywisetracker",
            name="truck_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
