# Generated by Django 4.2.11 on 2024-05-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0005_rename_comment_clrmodel_shipment_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="company_name",
            new_name="company",
        ),
        migrations.AlterField(
            model_name="clrmodel",
            name="shipper_reference",
            field=models.CharField(max_length=100),
        ),
    ]
