# Generated by Django 4.2.11 on 2024-05-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0006_citywisetracker_truck_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clrmodel",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="portstatus",
            name="filename",
        ),
        migrations.RemoveField(
            model_name="shipmentstatus",
            name="filename",
        ),
        migrations.AlterField(
            model_name="clrmodel",
            name="attachment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portstatus",
            name="attachment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipmentstatus",
            name="attachment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
