# Generated by Django 4.2.11 on 2024-05-25 03:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0006_rename_company_name_user_company_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="company",
            new_name="company_name",
        ),
    ]
