# Generated by Django 4.2.11 on 2024-05-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0007_remove_clrmodel_filename_remove_portstatus_filename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
