# Generated by Django 4.2.11 on 2024-05-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0007_rename_company_user_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(default="Lachin", max_length=50),
        ),
    ]
