# Generated by Django 4.2.11 on 2024-05-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0009_alter_clrmodel_book_no_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
