# Generated by Django 4.2.11 on 2024-05-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0009_expiringtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipmentstatus",
            name="docs",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipmentstatus",
            name="eta_arrival",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shipmentstatus",
            name="eta_departure",
            field=models.DateField(blank=True, null=True),
        ),
    ]
