# Generated by Django 4.2.11 on 2024-05-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0010_alter_user_company_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="company_name",
            field=models.CharField(default="Lachine", max_length=50),
        ),
    ]
