# Generated by Django 4.2.11 on 2024-05-14 04:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0012_alter_user_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
    ]
