# Generated by Django 4.2.11 on 2024-05-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0014_user_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.CharField(default="Lachine", max_length=50),
        ),
    ]
