# Generated by Django 4.2.11 on 2024-05-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0015_remove_user_company_name_user_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mobile_no",
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
