# Generated by Django 4.2.11 on 2024-05-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0016_remove_user_mobile_no_user_mobile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="mobile",
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_no",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="company",
            field=models.CharField(default="Lachine", max_length=50, null=True),
        ),
    ]
