# Generated by Django 4.2.11 on 2024-05-14 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0017_remove_user_mobile_user_mobile_no_alter_user_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="company",
            new_name="company_name",
        ),
    ]
