# Generated by Django 4.2.11 on 2024-05-14 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis", "0018_rename_company_user_company_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clrmodel",
            old_name="eta",
            new_name="etd",
        ),
    ]
